/// Display labels only. Controller policy and model allowlists remain authoritative.
const providerLabels = <String, String>{
  'ollama': 'Ollama (local)',
  'openrouter': 'OpenRouter (Nemotron free)',
  'anthropic': 'Anthropic API',
  'openai': 'OpenAI',
  'gemini': 'Google Gemini',
  'azure': 'Azure OpenAI',
  'bedrock': 'Amazon Bedrock',
  'vertex_ai': 'Google Vertex AI',
  'groq': 'Groq',
  'mistral': 'Mistral',
  'cohere': 'Cohere',
  'deepseek': 'DeepSeek',
  'xai': 'xAI',
  'together_ai': 'Together AI',
  'fireworks_ai': 'Fireworks AI',
  'perplexity': 'Perplexity',
  'cerebras': 'Cerebras',
  'sambanova': 'SambaNova',
  'nvidia_nim': 'NVIDIA NIM',
  'huggingface': 'Hugging Face',
  'replicate': 'Replicate',
  'ai21': 'AI21',
  'databricks': 'Databricks',
  'watsonx': 'IBM watsonx',
};
