"""Bilingual requirements narrative for the evidence-led Lycosa report.

Snapshot: 2026-09-18. Acceptance targets describe what should be verified;
they are not claims that a study, benchmark or production certification ran.
"""

PAGES = [
    {
        "section": 5,
        "title": {"en": "Research Methodology", "ar": "منهجية البحث"},
        "blocks": [
            {
                "heading": {"en": "A code-first design-science approach", "ar": "منهج علوم التصميم القائم على الشيفرة"},
                "en": "This report treats Lycosa as an engineering artefact investigated through a design-science lens: identify a practical coordination problem, construct a software response, and evaluate its observable properties. The object of analysis is the repository snapshot of 18 September 2026, not an imagined production deployment. The study is descriptive and analytical rather than a controlled experiment. It does not claim interviews, a participant cohort, an institutional review, or statistically generalisable user outcomes. Architectural interpretation is grounded in executable interfaces, domain models, service boundaries and deployment configuration, with project documentation used as supporting context rather than unquestioned proof. [L1–L6]",
                "ar": "يتناول هذا التقرير منصة Lycosa بوصفها منتجًا هندسيًا يُدرس بمنهج علوم التصميم: تحديد مشكلة عملية في التنسيق، وبناء استجابة برمجية لها، ثم تقييم خصائصها القابلة للملاحظة. ويتمثل موضوع التحليل في لقطة المستودع بتاريخ 18 سبتمبر 2026، وليس في نشر إنتاجي مفترض. والدراسة وصفية وتحليلية، وليست تجربة مضبوطة؛ فلا تدّعي إجراء مقابلات أو إشراك عينة من المشاركين أو الحصول على مراجعة مؤسسية أو تحقيق نتائج استخدام قابلة للتعميم الإحصائي. ويستند تفسير المعمارية إلى الواجهات التنفيذية ونماذج المجال وحدود الخدمات وإعدادات النشر، مع استخدام توثيق المشروع سياقًا داعمًا لا دليلًا مُسلّمًا بصحته. [L1–L6]",
            },
            {
                "heading": {"en": "Evidence collection and triangulation", "ar": "جمع الأدلة ومقارنتها"},
                "en": "Evidence is collected from six internal source groups: documentation, controller services and models, agent implementation, desktop implementation, automated tests, and infrastructure. A capability enters the implemented scope only when a corresponding execution path can be identified. Tests strengthen confidence in specific contracts, but test presence alone is not a successful execution result. Where documentation and code differ, the narrower demonstrable behaviour governs this report. Diagram elements are cross-checked against persistence models and request flow; conceptual simplification is explicitly separated from an exact deployment inventory. This makes the method reproducible without inventing stakeholder research. [L1–L6]",
                "ar": "تُجمع الأدلة من ست مجموعات داخلية: التوثيق، وخدمات المتحكم ونماذجه، وتنفيذ الوكيل، وتنفيذ التطبيق المكتبي، والاختبارات الآلية، والبنية التحتية. ولا تُدرج القدرة ضمن النطاق المنفذ إلا عند تحديد مسار تنفيذي يقابلها. وتعزز الاختبارات الثقة في عقود محددة، لكن وجود الاختبار لا يساوي نجاح تنفيذه. وعند اختلاف التوثيق والشيفرة، يعتمد التقرير السلوك الأضيق القابل للإثبات. وتُراجع عناصر المخططات مقابل نماذج التخزين وتدفق الطلبات، مع التمييز الصريح بين التبسيط المفاهيمي وقائمة مكونات النشر الفعلية. وبذلك تصبح المنهجية قابلة للتكرار دون اختلاق أبحاث مع أصحاب المصلحة. [L1–L6]",
            },
            {
                "heading": {"en": "Evaluation strategy and acceptance evidence", "ar": "استراتيجية التقييم وأدلة القبول"},
                "en": "Evaluation is organised in layers. Unit tests address schemas, routing decisions, evidence budgets and credential rules; integration tests exercise persistence, workflow transitions and protocol boundaries. Optional live smoke tests use synthetic content to distinguish transport success from answer quality, and desktop inspection checks presentation separately from backend correctness. A supported evidence question, an unsupported question, privacy rejection, missing credentials and a rejected approval gate form a minimum negative-and-positive test set. Proposed acceptance criteria below are deliberately falsifiable. An individual successful model response establishes that scenario only; it does not demonstrate universal factual grounding, provider availability or usability. [L2–L5]",
                "ar": "يُنظم التقييم في طبقات. تختبر اختبارات الوحدات المخططات وقرارات التوجيه وحدود الأدلة وقواعد بيانات الاعتماد، بينما تختبر اختبارات التكامل التخزين وانتقالات سير العمل وحدود البروتوكولات. وتستخدم الاختبارات الحية الاختيارية محتوى اصطناعيًا للتمييز بين نجاح الاتصال وجودة الإجابة، ويُفحص العرض المكتبي بصورة مستقلة عن صحة الخلفية. وتشكل مسألة تدعمها الأدلة، ومسألة غير مدعومة، ورفض الإرسال لأسباب الخصوصية، وغياب بيانات الاعتماد، ورفض بوابة الموافقة حدًا أدنى لاختبارات النجاح والفشل. ومعايير القبول المقترحة أدناه قابلة للدحض عمدًا. فنجاح إجابة منفردة يثبت ذلك السيناريو فقط، ولا يبرهن على الارتكاز المعرفي الشامل أو توافر المزود أو سهولة الاستخدام. [L2–L5]",
            },
            {
                "heading": {"en": "Validity, ethics and reproducibility", "ar": "الصلاحية والأخلاقيات وقابلية التكرار"},
                "en": "Internal validity is limited by mocked dependencies and implementation-coupled tests. External validity is limited by hardware, model size, network conditions and a small set of synthetic scenarios. Accordingly, performance thresholds are future acceptance targets unless a dated run documents conditions and measurements. Reproduction should record commit identifier, dependency versions, model identifier, resource limits, test command and outcome. Provider secrets must never enter the report or repository; real private documents must not be sent to external inference services merely to demonstrate the architecture. Outstanding discrepancies become explicit limitations or backlog items, not silently upgraded claims. [L3, L5, L6]",
                "ar": "تحد الاعتماديات المحاكية والاختبارات المرتبطة بالتنفيذ من الصلاحية الداخلية، بينما تحد اختلافات العتاد وحجم النموذج وظروف الشبكة وقلة السيناريوهات الاصطناعية من الصلاحية الخارجية. لذلك تُعد حدود الأداء أهداف قبول مستقبلية ما لم يوثّق تنفيذ مؤرخ ظروف القياس ونتائجه. وينبغي تسجيل معرّف الالتزام وإصدارات الاعتماديات ومعرّف النموذج وحدود الموارد وأمر الاختبار ونتيجته عند إعادة الإنتاج. ويجب ألا تدخل أسرار المزود في التقرير أو المستودع، وألا تُرسل مستندات خاصة حقيقية إلى خدمات استدلال خارجية لمجرد عرض المعمارية. وتُسجل التناقضات المتبقية قيودًا أو أعمالًا مؤجلة، ولا تتحول ضمنيًا إلى ادعاءات بقدرات مكتملة. [L3، L5، L6]",
            },
        ],
    },
    {
        "section": 6,
        "title": {"en": "User Stories — Access and Execution", "ar": "قصص المستخدم — الوصول والتنفيذ"},
        "blocks": [
            {
                "heading": {"en": "Scenario-based specification", "ar": "توصيف قائم على السيناريوهات"},
                "en": "These stories translate repository-observed roles and journeys into testable expectations; they are analyst-derived, not quotations from a user study. Acceptance clauses specify observable outcomes rather than internal implementation choices. The administrator governs access and provider configuration, while authorised operators submit work and inspect results. Implementation status describes available code paths, not a claim that every desktop scenario has been retested for this report. [L2, L4, L5]",
                "ar": "تحول هذه القصص الأدوار ومسارات الاستخدام الملحوظة في المستودع إلى توقعات قابلة للاختبار؛ فهي مستنبطة تحليليًا وليست اقتباسات من دراسة مستخدمين. وتحدد شروط القبول نتائج ظاهرة، لا اختيارات تنفيذ داخلية. ويدير المسؤول الوصول وإعداد المزودين، بينما يرسل المشغلون المخولون المهام ويفحصون النتائج. وتصف حالة التنفيذ مسارات برمجية متاحة، ولا تعني إعادة اختبار كل سيناريو مكتبي لأغراض هذا التقرير. [L2، L4، L5]",
            },
            {
                "heading": {"en": "US01 · Establish an authorised session", "ar": "US01 · إنشاء جلسة مخولة"},
                "en": "As an operator, I want to select my controller profile and authenticate so that I can manage the intended environment. Given a reachable controller and valid account, when I sign in, then the dashboard exposes only operations permitted by the server-side role. Given an invalid credential or expired session, when a protected request is made, then access is denied without disclosing credential values. Signing out must invalidate the applicable application session; it does not remove a controller-wide provider credential. Status: implemented authentication and profile paths; explicit role checks remain authoritative. [L2, L4]",
                "ar": "بصفتي مشغلًا، أريد اختيار ملف المتحكم وتسجيل الدخول كي أدير البيئة المقصودة. بفرض وجود متحكم متاح وحساب صالح، عندما أسجل الدخول، فيجب أن تتاح العمليات التي يسمح بها الدور على الخادم فقط. وبفرض وجود بيانات اعتماد غير صالحة أو جلسة منتهية، عندما يُطلب مورد محمي، فيجب رفض الوصول دون كشف بيانات الاعتماد. ويجب أن ينهي تسجيل الخروج جلسة التطبيق المعنية؛ لكنه لا يحذف مفتاح المزود المشترك على المتحكم. الحالة: مسارات المصادقة والملفات منفذة، وتبقى صلاحيات الخادم المرجع الحاسم. [L2، L4]",
            },
            {
                "heading": {"en": "US02 · Enrol and inspect a device", "ar": "US02 · ضم جهاز وفحصه"},
                "en": "As an administrator, I want to issue a node credential and inspect a joining agent so that device participation is deliberate. Given a valid node key, when an agent registers and sends Usage telemetry, then the node inventory exposes identity, hardware and availability with a role recommendation. Given only an mDNS discovery announcement, when the device is discovered, then it is not automatically trusted or enrolled. Revoking its key must deny subsequent authenticated access. Status: implemented enrolment, advisory discovery and telemetry; role labels alone do not prove corresponding specialist tools exist. [L2–L4]",
                "ar": "بصفتي مسؤولًا، أريد إصدار بيانات اعتماد لعقدة وفحص الوكيل المنضم حتى تكون مشاركة الأجهزة مقصودة. بفرض وجود مفتاح عقدة صالح، عندما يسجل الوكيل ويرسل قياسات الاستخدام، فيجب أن يعرض سجل العقد هويته وعتاده وتوافره مع توصية بالدور. وبفرض وجود إعلان اكتشاف mDNS فقط، عندما يُكتشف الجهاز، فلا يجوز الوثوق به أو ضمه تلقائيًا. ويجب أن يمنع إلغاء مفتاحه الوصول المخول اللاحق. الحالة: الضم والاكتشاف الاسترشادي والقياسات منفذة؛ ولا تثبت أسماء الأدوار وحدها وجود أدوات تخصصية تقابلها. [L2–L4]",
            },
            {
                "heading": {"en": "US03 · Run a local inference task", "ar": "US03 · تنفيذ مهمة استدلال محلية"},
                "en": "As an operator, I want to submit a prompt to an eligible local model and understand the outcome. Given an online dispatchable node with the requested model, when I submit an Ollama task, then the controller selects a compatible candidate and persists the result or failure. Given a candidate execution failure, then the recorded attempt trace explains the attempted node path. If no candidate qualifies, the task must fail visibly rather than pretend success. Status: implemented routing and task history; synchronous request execution is not a durable background job queue. [L2, L4]",
                "ar": "بصفتي مشغلًا، أريد إرسال طلب إلى نموذج محلي مؤهل وفهم النتيجة. بفرض وجود عقدة متصلة قابلة للتنفيذ والنموذج المطلوب مثبت عليها، عندما أرسل مهمة Ollama، فيجب أن يختار المتحكم مرشحًا متوافقًا ويحفظ النتيجة أو الفشل. وعند فشل محاولة التنفيذ، يجب أن يوضح سجل المحاولات العقدة التي جرى استخدامها. وإذا لم يتأهل أي مرشح، فيجب أن تفشل المهمة بوضوح بدل إظهار نجاح وهمي. الحالة: التوجيه وسجل المهام منفذان؛ والتنفيذ المتزامن مع الطلب ليس طابور وظائف خلفية دائمًا. [L2، L4]",
            },
            {
                "heading": {"en": "US04 · Opt into constrained cloud execution", "ar": "US04 · اختيار تنفيذ سحابي مقيد"},
                "en": "As an operator, I want an explicitly configured free-model route when local compute is unavailable. Given an administrator-configured OpenRouter credential, when I select the supported NVIDIA model and submit non-private synthetic input, then controller-side execution records output and numeric usage. Given requires_privacy=true, then external execution is rejected before sending inference content. A missing credential, provider rejection or unavailable free route must remain visible, without an unrequested paid fallback. Status: implemented exact-model path; configured credentials are not evidence of remote validity. [L2, L4]",
                "ar": "بصفتي مشغلًا، أريد مسارًا مهيأ صراحة لنموذج مجاني عندما لا تتوافر حوسبة محلية. بفرض أن المسؤول أعد مفتاح OpenRouter، عندما أختار نموذج NVIDIA المدعوم وأرسل مدخلًا اصطناعيًا غير خاص، فيجب أن يسجل التنفيذ عبر المتحكم المخرج وبيانات الاستخدام الرقمية. وبفرض أن requires_privacy=true، فيجب رفض التنفيذ الخارجي قبل إرسال محتوى الاستدلال. ويجب إظهار غياب المفتاح أو رفض المزود أو تعذر المسار المجاني دون التحول إلى بديل مدفوع غير مطلوب. الحالة: مسار النموذج المحدد منفذ؛ ولا يثبت إعداد المفتاح صلاحيته لدى الخدمة الخارجية. [L2، L4]",
            },
        ],
    },
    {
        "section": 6,
        "title": {"en": "User Stories — Knowledge and Coordination", "ar": "قصص المستخدم — المعرفة والتنسيق"},
        "blocks": [
            {
                "heading": {"en": "Knowledge is an explicit trust boundary", "ar": "المعرفة حد ثقة صريح"},
                "en": "The following stories distinguish collection retrieval, task-context injection and the agent's separate evidence-answering contract. These are related capabilities, but they are not interchangeable interfaces. Source identifiers support inspection; they are not a formal proof that an answer follows from a passage. Human approval governs workflow continuation rather than guaranteeing the truth or safety of every generated statement. [L2, L3]",
                "ar": "تميز القصص التالية بين الاسترجاع من مجموعات المعرفة، وإضافة السياق إلى المهمة، وعقد الإجابة المستقلة من الأدلة لدى الوكيل. وهذه قدرات مترابطة، لكنها ليست واجهات متبادلة. وتساعد معرّفات المصادر على الفحص، لكنها لا تمثل برهانًا رسميًا على استنتاج الإجابة من النص. كما تضبط الموافقة البشرية استمرار سير العمل، ولا تضمن صحة كل عبارة مولدة أو سلامتها. [L2، L3]",
            },
            {
                "heading": {"en": "US05 · Build and query a knowledge collection", "ar": "US05 · بناء مجموعة معرفة والاستعلام عنها"},
                "en": "As a knowledge operator, I want to upload a supported document and query a named collection so that retrieval is inspectable and scoped. Given a collection and a valid synthetic document, when ingestion succeeds, then document metadata and searchable vector chunks are available. When I retrieve a known phrase within that collection, then results include source, collection and relevance score. Given an unknown collection name, then an explicit error is returned rather than silently broadening the search. Status: implemented controller-managed ingestion and retrieval; fully distributed multi-node vector federation is outside this implementation. [L2, L4]",
                "ar": "بصفتي مشغل معرفة، أريد رفع مستند مدعوم والاستعلام عن مجموعة مسماة كي يكون الاسترجاع قابلًا للفحص ومحدد النطاق. بفرض وجود مجموعة ومستند اصطناعي صالح، عندما ينجح الإدخال، فيجب أن تتوافر بيانات المستند ومقاطعه المتجهية القابلة للبحث. وعندما أسترجع عبارة معروفة ضمن تلك المجموعة، فيجب أن تتضمن النتائج المصدر والمجموعة ودرجة الصلة. وبفرض أن اسم المجموعة غير معروف، فيجب إرجاع خطأ صريح بدل توسيع نطاق البحث بصمت. الحالة: الإدخال والاسترجاع عبر المتحكم منفذان؛ أما اتحاد الفهارس المتجهية الموزع بالكامل عبر العقد فخارج هذا التنفيذ. [L2، L4]",
            },
            {
                "heading": {"en": "US06 · Ask an evidence-bounded local agent", "ar": "US06 · سؤال وكيل محلي ضمن أدلة محددة"},
                "en": "As a developer integrating the agent, I want to supply retrieved passages and receive an answer with inspectable citations. Given an installed local model and relevant passages, when I call /rag/answer or the optional MCP answer_from_context tool, then the response contains source mapping, citation status and truncation information. Given no surviving evidence after filtering, then the agent refuses without model generation. Unknown citation IDs must be flagged, not manufactured into valid sources. Status: implemented bounded contract; the desktop's existing controller RAG path is not automatically migrated to this endpoint. [L3]",
                "ar": "بصفتي مطورًا يدمج الوكيل، أريد تقديم مقاطع مسترجعة والحصول على إجابة ذات استشهادات قابلة للفحص. بفرض وجود نموذج محلي مثبت ومقاطع ذات صلة، عندما أستدعي /rag/answer أو أداة MCP الاختيارية answer_from_context، فيجب أن تتضمن الاستجابة خريطة المصادر وحالة الاستشهاد ومعلومات الاقتطاع. وبفرض عدم بقاء أدلة بعد التصفية، فيجب أن يمتنع الوكيل عن الإجابة دون تشغيل النموذج. ويجب تمييز معرّفات الاستشهاد المجهولة، لا تحويلها إلى مصادر مختلقة صالحة. الحالة: العقد المقيد منفذ؛ ولم يُنقل مسار الاسترجاع الحالي عبر المتحكم في التطبيق المكتبي تلقائيًا إلى هذه الواجهة. [L3]",
            },
            {
                "heading": {"en": "US07 · Control a multi-step workflow", "ar": "US07 · التحكم في سير عمل متعدد الخطوات"},
                "en": "As an operator, I want retrieval and task steps to share context while pausing for a human decision. Given a valid workflow containing an approval step, when execution reaches that step, then the run is persisted as paused and the approval step as pending_approval; downstream steps do not execute. When an authorised operator approves, then execution resumes; when rejected, then the run records failure without executing the blocked continuation. Retry attempts must remain inspectable. Status: implemented workflow state transitions, conditions and bounded task fan-out; no autonomous agent planning or crash-proof distributed workflow guarantee is implied. [L2, L4, L5]",
                "ar": "بصفتي مشغلًا، أريد أن تتشارك خطوات الاسترجاع والمهام السياق مع التوقف لقرار بشري. بفرض وجود سير عمل صالح يحتوي على خطوة موافقة، عندما يصل التنفيذ إليها، فيجب حفظ حالة التشغيل paused وحالة خطوة الموافقة pending_approval، وألا تُنفذ الخطوات التالية. وعندما يوافق مشغل مخول، فيستأنف التنفيذ؛ وعندما يرفض، فيُسجل الفشل دون تنفيذ الاستمرار المحجوب. ويجب أن تبقى محاولات الإعادة قابلة للفحص. الحالة: انتقالات الحالة والشروط والتفرع المتوازي المقيد منفذة؛ ولا يعني ذلك تخطيطًا ذاتيًا للوكيل أو ضمانًا موزعًا مقاومًا للأعطال. [L2، L4، L5]",
            },
            {
                "heading": {"en": "US08 · Diagnose execution and availability", "ar": "US08 · تشخيص التنفيذ والتوافر"},
                "en": "As an administrator, I want task history, node Usage and audit events to explain an operational failure. Given a failed task or stale node, when I inspect the dashboard and authorised API records, then I can distinguish unavailable capacity, rejected policy and runtime error where recorded. Provider credentials must remain absent from visible history and audit details. Status: implemented operational surfaces; a node shown offline still requires runtime investigation. Proposed usability acceptance: a new operator completes this diagnosis using the report's synthetic fixture without editing a database or reading a secret. [L2, L4–L6]",
                "ar": "بصفتي مسؤولًا، أريد أن يوضح سجل المهام واستخدام العقد وأحداث التدقيق سبب الفشل التشغيلي. بفرض وجود مهمة فاشلة أو عقدة لم ترسل تحديثًا حديثًا، عندما أفحص لوحة التحكم وسجلات الواجهة المخولة، فيجب أن أميز بين غياب السعة ورفض السياسة وخطأ وقت التشغيل حيثما سُجلت هذه المعلومات. ويجب ألا تظهر مفاتيح المزود في السجلات المرئية أو تفاصيل التدقيق. الحالة: واجهات التشغيل منفذة؛ لكن ظهور العقدة غير متصلة يستلزم فحص التشغيل. معيار سهولة الاستخدام المقترح: إتمام مشغل جديد لهذا التشخيص بالبيانات الاصطناعية دون تعديل قاعدة البيانات أو قراءة سر. [L2، L4–L6]",
            },
        ],
    },
    {
        "section": 7,
        "title": {"en": "Functional Requirements — Control Plane", "ar": "المتطلبات الوظيفية — طبقة التحكم"},
        "blocks": [
            {
                "heading": {"en": "Status and acceptance convention", "ar": "اصطلاح الحالة والقبول"},
                "en": "The requirements below restate the current implementation as verifiable obligations. Implemented means a source-level execution path exists; proposed acceptance means the criterion is a recommended release gate, not an already measured outcome. This distinction prevents design intent from being misreported as demonstrated reliability. Requirement identifiers are report-local and should be mapped to issue tracking before formal baselining. [L1, L5]",
                "ar": "تعيد المتطلبات الآتية صياغة التنفيذ الحالي في صورة التزامات قابلة للتحقق. وتعني حالة «منفذ» وجود مسار تنفيذي في الشيفرة؛ أما «القبول المقترح» فيعني معيارًا موصى به قبل الإصدار، لا نتيجة مقاسة مسبقًا. ويمنع هذا الفصل عرض النية التصميمية بوصفها موثوقية مثبتة. ومعرّفات المتطلبات خاصة بهذا التقرير، وينبغي ربطها بتتبع المشكلات قبل اعتماد خط أساس رسمي. [L1، L5]",
            },
            {
                "heading": {"en": "FR01 · Authentication and authorisation", "ar": "FR01 · المصادقة والتخويل"},
                "en": "The controller shall authenticate supported principals and enforce endpoint roles independently of desktop presentation. Status: implemented account sessions, API-key handling and role checks. Proposed acceptance: exercise valid, invalid, expired and revoked credentials against every protected route category; all unauthorised operations must be denied and authorised operations must retain their intended access. Administrative provider management must reject operator and node principals. Test records must contain credential references only, never reusable secret values. [L2, L5]",
                "ar": "يجب أن يصادق المتحكم على الهويات المدعومة وأن يفرض أدوار الواجهات بصورة مستقلة عن العرض المكتبي. الحالة: جلسات الحساب ومفاتيح الواجهة وفحص الأدوار منفذة. القبول المقترح: اختبار بيانات اعتماد صالحة وغير صالحة ومنتهية وملغاة على جميع فئات المسارات المحمية؛ مع رفض كل عملية غير مخولة وإبقاء الوصول المقصود للعمليات المخولة. ويجب أن ترفض إدارة المزودين أدوار المشغل والعقدة. ولا تتضمن سجلات الاختبار إلا مراجع لبيانات الاعتماد، دون أسرار قابلة لإعادة الاستخدام. [L2، L5]",
            },
            {
                "heading": {"en": "FR02 · Node enrolment and Usage", "ar": "FR02 · ضم العقد وقياسات الاستخدام"},
                "en": "The platform shall enrol authenticated agents, retain hardware and runtime metadata, and derive operational availability from reported Usage freshness. Status: implemented registration, telemetry and advisory discovery. Proposed acceptance: register a synthetic node, update its metrics, advance time beyond the configured stale threshold, and verify the expected availability transition. Repeat registration must follow the documented identity contract without granting an unrelated key control of an existing node. Discovery alone must never establish dispatch authority. [L2, L3, L5]",
                "ar": "يجب أن تضم المنصة الوكلاء المخولين، وتحفظ بيانات العتاد وبيئات التشغيل، وتستنتج التوافر التشغيلي من حداثة تقارير الاستخدام. الحالة: التسجيل والقياسات والاكتشاف الاسترشادي منفذة. القبول المقترح: تسجيل عقدة اصطناعية، وتحديث قياساتها، وتجاوز حد التقادم المضبوط، ثم التحقق من انتقال حالة التوافر المتوقع. ويجب أن يلتزم تكرار التسجيل بعقد الهوية الموثق دون منح مفتاح غير ذي صلة التحكم في عقدة موجودة. ولا يجوز أن يمنح الاكتشاف وحده سلطة التنفيذ. [L2، L3، L5]",
            },
            {
                "heading": {"en": "FR03 · Explainable candidate selection", "ar": "FR03 · اختيار مرشحين قابل للتفسير"},
                "en": "Local tasks shall be routed using dispatchability, role compatibility, installed models and available resource evidence, subject to requested privacy and memory constraints. Status: implemented heuristic routing; no global GPU reservation is claimed. Proposed acceptance: use a deterministic candidate fixture covering stale telemetry, absent models, insufficient RAM or VRAM and explicit CPU fallback. Each selected candidate must satisfy the enforced filters, and the routing explanation must identify the applied considerations. Removing all eligible candidates must produce a visible failure. [L2, L5]",
                "ar": "يجب توجيه المهام المحلية وفق قابلية التنفيذ وتوافق الدور والنماذج المثبتة وأدلة الموارد المتاحة، مع مراعاة قيود الخصوصية والذاكرة المطلوبة. الحالة: التوجيه الاسترشادي منفذ؛ ولا يُدعى وجود حجز شامل لمعالجات الرسوميات. القبول المقترح: استخدام مجموعة مرشحين حتمية تشمل قياسات متقادمة ونماذج غائبة وذاكرة غير كافية وبديل المعالج المركزي المصرح به. ويجب أن يستوفي كل مرشح مختار المرشحات المطبقة وأن يوضح تفسير التوجيه الاعتبارات المستخدمة. ويجب أن يؤدي غياب المرشحين المؤهلين إلى فشل ظاهر. [L2، L5]",
            },
            {
                "heading": {"en": "FR04 · Persistent task outcomes", "ar": "FR04 · حفظ نتائج المهام"},
                "en": "Task submission shall preserve input metadata, state transitions and result or error, with local execution attempts linked to participating nodes. Status: implemented synchronous dispatch and persisted history; direct OpenRouter tasks need no node execution row. Proposed acceptance: verify success, exhausted local failover and client-disconnect scenarios. Each terminal record must have the appropriate completion state and recoverable detail. A disconnected HTTP client must not by itself cancel shielded execution, but process termination is outside that guarantee. [L2, L5]",
                "ar": "يجب أن يحفظ إرسال المهمة بيانات الإدخال وانتقالات الحالة والنتيجة أو الخطأ، مع ربط محاولات التنفيذ المحلية بالعقد المشاركة. الحالة: التنفيذ المتزامن والسجل الدائم منفذان؛ ولا تحتاج مهمة OpenRouter المباشرة إلى سجل تنفيذ مرتبط بعقدة. القبول المقترح: التحقق من النجاح واستنفاد البدائل المحلية وانقطاع العميل. ويجب أن تتضمن كل نتيجة نهائية حالة الإكمال المناسبة وتفاصيل قابلة للاسترجاع. ولا ينبغي أن يلغي انقطاع عميل HTTP وحده التنفيذ المحمي، لكن إنهاء العملية خارج هذا الضمان. [L2، L5]",
            },
            {
                "heading": {"en": "FR05 · Controlled provider credentials", "ar": "FR05 · إدارة مقيدة لمفاتيح المزودين"},
                "en": "Administrators shall explicitly manage controller-owned provider credentials through supported secure-vault or restricted session storage. Status: implemented; OpenRouter session storage requires one worker and disappears on restart. Proposed acceptance: verify role denial, invalid-value rejection, storage failure and successful removal of the selected storage entry. Status responses must reveal configuration only. The desktop must refuse credential submission over remote plaintext HTTP and redirects; deployment TLS remains an operator responsibility rather than a server-enforced universal transport guarantee. [L2, L4, L5]",
                "ar": "يجب أن يدير المسؤولون مفاتيح المزودين التابعة للمتحكم صراحة عبر الخزنة الآمنة المدعومة أو تخزين الجلسة المقيد. الحالة: منفذ؛ ويتطلب تخزين جلسة OpenRouter عاملًا واحدًا ويزول عند إعادة التشغيل. القبول المقترح: التحقق من رفض الدور والقيم غير الصالحة وفشل التخزين وحذف السجل المحدد بنجاح. ويجب ألا تكشف استجابات الحالة سوى وجود الإعداد. كما يجب أن يرفض التطبيق إرسال المفتاح عبر HTTP بعيد غير مشفر أو إعادة التوجيه؛ ويبقى تشفير النشر مسؤولية المشغل، لا ضمانًا عامًا يفرضه الخادم. [L2، L4، L5]",
            },
        ],
    },
    {
        "section": 7,
        "title": {"en": "Functional Requirements — Knowledge and Workflows", "ar": "المتطلبات الوظيفية — المعرفة وسير العمل"},
        "blocks": [
            {
                "heading": {"en": "FR06 · Document lifecycle and retrieval", "ar": "FR06 · دورة المستند والاسترجاع"},
                "en": "The knowledge service shall manage collections, extract supported document content, generate embeddings and retrieve ranked chunks with provenance. Status: implemented controller-managed relational metadata and Qdrant vectors. Proposed acceptance: ingest a deterministic fixture, verify searchable chunks and source identifiers, retrieve within a named collection, and test collection deletion, including its documents, embedding jobs and vectors across metadata and vector storage. Unknown collections must fail explicitly. Cross-collection retrieval must be described as merged controller-managed search, not distributed vector federation. Limits and supported formats must be taken from deployed configuration and loaders. [L2, L5]",
                "ar": "يجب أن تدير خدمة المعرفة المجموعات، وتستخرج محتوى المستندات المدعومة، وتولد التضمينات، وتسترجع المقاطع المرتبة مع بيانات مصدرها. الحالة: إدارة البيانات العلائقية ومتجهات Qdrant عبر المتحكم منفذة. القبول المقترح: إدخال عينة حتمية، والتحقق من المقاطع القابلة للبحث ومعرّفات مصادرها، والاسترجاع ضمن مجموعة مسماة، واختبار حذف المجموعة ووثائقها ووظائف تضمينها ومتجهاتها من التخزين العلائقي والمتجهي. ويجب أن تفشل المجموعات المجهولة صراحة. ويوصف البحث عبر المجموعات بأنه بحث مدمج يديره المتحكم، لا اتحاد متجهي موزع. وتُستمد الحدود والصيغ المدعومة من إعداد النشر وأدوات التحميل. [L2، L5]",
            },
            {
                "heading": {"en": "FR07 · Explicit retrieval-to-generation policy", "ar": "FR07 · سياسة صريحة لربط الاسترجاع بالتوليد"},
                "en": "Controller task and workflow routes shall pass the specified knowledge query and collection into retrieval before contextual generation. Status: implemented legacy context injection, with fail-closed retrieval errors on the external OpenRouter route. Proposed acceptance: assert that a scoped fixture reaches the intended generation request, an unknown collection prevents external inference, and requires_privacy blocks the cloud path. An empty valid retrieval and a retrieval exception are distinct cases and must be evaluated separately. This requirement does not assert that legacy controller results expose the agent's structured citation contract. [L2, L5]",
                "ar": "يجب أن تمرر مسارات المهام وسير العمل في المتحكم استعلام المعرفة والمجموعة المحددين إلى الاسترجاع قبل التوليد المدعوم بالسياق. الحالة: إضافة السياق التقليدية منفذة، مع إيقاف التنفيذ عند أخطاء الاسترجاع في مسار OpenRouter الخارجي. القبول المقترح: إثبات وصول عينة المجموعة المحددة إلى طلب التوليد، ومنع المجموعة المجهولة للاستدلال الخارجي، وحجب requires_privacy للمسار السحابي. ويختلف الاسترجاع الصالح الخالي من النتائج عن استثناء الاسترجاع، ويجب تقييمهما منفصلين. ولا يفترض هذا المتطلب أن نتائج المتحكم التقليدية تتضمن عقد الاستشهاد المنظم لدى الوكيل. [L2، L5]",
            },
            {
                "heading": {"en": "FR08 · Bounded evidence answering", "ar": "FR08 · الإجابة ضمن أدلة مقيدة"},
                "en": "The agent shall accept at most 20 supplied evidence chunks, filter and deduplicate them, apply the requested character budget and expose citation diagnostics. Status: implemented local /rag/answer and shared MCP logic; retrieval remains caller-owned. Proposed acceptance: exercise empty evidence, filtered evidence, clipping, missing models, unknown citation IDs, refusal and runtime timeout. Inputs exceeding schema limits must be rejected before inference. Supported and unsupported fact fixtures must evaluate answer content independently of citation validity. Source-ID membership alone shall never be labelled factual-entailment verification. [L3, L5]",
                "ar": "يجب أن يقبل الوكيل عشرين مقطع دليل كحد أقصى، وأن يصفيها ويزيل تكرارها ويطبق حد الأحرف المطلوب ويعرض تشخيص الاستشهاد. الحالة: واجهة /rag/answer المحلية والمنطق المشترك مع MCP منفذان، بينما يبقى الاسترجاع مسؤولية المستدعي. القبول المقترح: اختبار الأدلة الفارغة والمصفاة والاقتطاع والنماذج المفقودة ومعرّفات الاستشهاد المجهولة والامتناع وانتهاء المهلة. ويجب رفض المدخلات المتجاوزة لحدود المخطط قبل الاستدلال. ويجب تقييم محتوى الإجابة للحالات المدعومة وغير المدعومة بمعزل عن صلاحية الاستشهاد. ولا يجوز وصف انتماء معرّف المصدر وحده بأنه تحقق من صحة الاستنتاج. [L3، L5]",
            },
            {
                "heading": {"en": "FR09 · Governed workflow execution", "ar": "FR09 · تنفيذ سير عمل خاضع للضبط"},
                "en": "The workflow engine shall validate definitions, propagate declared step context, persist run and attempt state, and enforce approval barriers. Status: implemented sequential execution, conditions, retries, parallel task substeps and approval continuation. Proposed acceptance: cover a successful run, a failing retried task, a skipped condition, parallel branch failure, approval and rejection. No downstream operation may execute before an approval decision. Rejected runs must remain inspectable, with no accidental re-entry into the blocked continuation. Durable restart recovery, distributed locking and an asynchronous queue require separate design and verification. [L2, L5]",
                "ar": "يجب أن يتحقق محرك سير العمل من التعريفات، وينقل سياق الخطوات المعلن، ويحفظ حالة التشغيل والمحاولات، ويفرض حواجز الموافقة. الحالة: التنفيذ المتسلسل والشروط وإعادة المحاولة والمهام الفرعية المتوازية والاستمرار بعد الموافقة منفذة. القبول المقترح: تغطية تشغيل ناجح، ومهمة فاشلة مع إعادة المحاولة، وشرط متجاوز، وفشل فرع متوازٍ، والموافقة والرفض. ولا يجوز تنفيذ أي عملية لاحقة قبل قرار الموافقة. ويجب أن تبقى التشغيلات المرفوضة قابلة للفحص دون عودة عرضية إلى الاستمرار المحجوب. ويتطلب التعافي الدائم بعد إعادة التشغيل والقفل الموزع والطابور غير المتزامن تصميمًا وتحققًا مستقلين. [L2، L5]",
            },
            {
                "heading": {"en": "FR10 · Constrained MCP interoperability", "ar": "FR10 · تكامل MCP محدود القدرات"},
                "en": "The optional agent companion shall expose capability inspection, local model enumeration and evidence answering through stdio MCP. Status: implemented three-tool server, launched as a separate local process. Proposed acceptance: complete a real client handshake, enumerate exactly the supported tools, invoke valid requests, reject invalid schemas and reject an unknown shell-execution tool. The companion must close its runtime client on shutdown. It shall not silently gain arbitrary filesystem access, external MCP connections, autonomous tool loops or the registered service's Usage identity. Those capabilities remain outside scope rather than hidden extensions. [L3, L5]",
                "ar": "يجب أن يتيح مرافق الوكيل الاختياري فحص القدرات وحصر النماذج المحلية والإجابة من الأدلة عبر MCP باستخدام الإدخال والإخراج القياسيين. الحالة: خادم بثلاث أدوات منفذ ويعمل بوصفه عملية محلية مستقلة. القبول المقترح: إتمام مصافحة عميل حقيقية، وحصر الأدوات المدعومة فقط، وتنفيذ الطلبات الصالحة، ورفض المخططات غير الصالحة وأداة تنفيذ أوامر مجهولة. ويجب أن يغلق المرافق عميل التشغيل عند الإنهاء. ولا يجوز أن يكتسب ضمنيًا وصولًا عامًا للملفات أو اتصالات MCP خارجية أو حلقات أدوات ذاتية أو هوية استخدام الخدمة المسجلة. وتبقى هذه القدرات خارج النطاق، لا امتدادات مخفية. [L3، L5]",
            },
        ],
    },
    {
        "section": 7,
        "title": {"en": "Non-Functional Requirements and Release Gates", "ar": "المتطلبات غير الوظيفية ومعايير الإصدار"},
        "blocks": [
            {
                "heading": {"en": "NFR01 · Security", "ar": "NFR01 · الأمن"},
                "en": "Status: role checks, agent tokens and secret redaction are implemented; comprehensive security assurance remains proposed. Acceptance target: zero successful unauthorised operations in the route-role matrix and zero credential values in captured application logs, persisted task output and audit fixtures. Test hostile redirects and runtime errors. Internet exposure requires a separate deployment hardening review. [L2–L6]",
                "ar": "الحالة: فحص الأدوار ورموز الوكلاء وحجب الأسرار منفذة؛ أما الضمان الأمني الشامل فمقترح. هدف القبول: عدم نجاح أي عملية غير مخولة في مصفوفة المسارات والأدوار، وعدم ظهور أسرار في السجلات والمخرجات المحفوظة وبيانات التدقيق الاختبارية. وتُختبر إعادة التوجيه الخبيثة وأخطاء التشغيل. ويتطلب التعرض للإنترنت مراجعة تحصين مستقلة. [L2–L6]",
            },
            {
                "heading": {"en": "NFR02 · Privacy and data minimisation", "ar": "NFR02 · الخصوصية وتقليل البيانات"},
                "en": "Status: explicit privacy gating and restricted provider-output persistence are implemented. Acceptance target: every external-provider privacy fixture produces zero outbound inference calls; persisted provider metadata contains only the intended numeric usage and routing fields. Proposed production work: document retention periods, deletion responsibilities and controller-wide credential-sharing consent. No tenant-isolation certification is claimed. [L2, L5]",
                "ar": "الحالة: بوابة الخصوصية الصريحة وتقييد حفظ مخرجات المزود منفذان. هدف القبول: ألا ينتج أي اختبار خصوصية للمزود الخارجي اتصال استدلال صادرًا، وأن تقتصر بياناته الوصفية المحفوظة على حقول الاستخدام الرقمية والتوجيه المقصودة. والعمل الإنتاجي المقترح: توثيق مدد الاحتفاظ ومسؤوليات الحذف والموافقة على مشاركة مفاتيح المتحكم. ولا يُدعى اعتماد عزل المستأجرين. [L2، L5]",
            },
            {
                "heading": {"en": "NFR03 · Predictable bounded execution", "ar": "NFR03 · تنفيذ محدود وقابل للتوقع"},
                "en": "Status: agent model-list and generation deadlines are 5 and 90 seconds; grounded HTTP and MCP calls each have a two-request concurrency limit. Acceptance target: use controlled slow adapters to verify deadlines, third-request rejection and counter release after cancellation. Proposed benchmark: report p50 and p95 separately for retrieval and inference on declared hardware; no latency achievement is asserted. [L3, L5]",
                "ar": "الحالة: مهلة قائمة النماذج خمس ثوانٍ والتوليد تسعون ثانية؛ ولكل من HTTP وMCP حد تزامن مستقل بطلبين للإجابة من الأدلة. هدف القبول: استخدام محاكيات بطيئة للتحقق من المهل ورفض الطلب الثالث وتحرير العدادات بعد الإلغاء. والقياس المقترح: عرض p50 وp95 للاسترجاع والاستدلال منفصلين على عتاد معلن، دون ادعاء تحقيق زمن معين. [L3، L5]",
            },
            {
                "heading": {"en": "NFR04 · Reliability and recovery", "ar": "NFR04 · الموثوقية والتعافي"},
                "en": "Status: recorded attempts, local failover and persisted workflow states exist. Acceptance target: fault-injection fixtures end in a truthful terminal or approval state with attributable error detail. Proposed production gate: demonstrate backup restoration and document recovery objectives. Client-disconnect shielding must not be presented as recovery from controller process loss, power failure or an unavailable database. [L2, L5, L6]",
                "ar": "الحالة: تتوافر سجلات المحاولات والبدائل المحلية وحالات سير العمل المحفوظة. هدف القبول: انتهاء اختبارات حقن الأعطال بحالة نهائية أو انتظار موافقة تعكس الواقع، مع تفاصيل خطأ واضحة. ومعيار الإنتاج المقترح: إثبات استعادة النسخ الاحتياطية وتوثيق أهداف التعافي. ولا يُعرض الحماية من انقطاع العميل بوصفها تعافيًا من توقف المتحكم أو انقطاع الطاقة أو قاعدة البيانات. [L2، L5، L6]",
            },
            {
                "heading": {"en": "NFR05 · Observability and auditability", "ar": "NFR05 · قابلية الرصد والتدقيق"},
                "en": "Status: task history, Usage telemetry, audit records, metrics and dashboard events are implemented. Acceptance target: each test task and workflow can be traced by identifier from submission to stored outcome, and metric counters reflect controlled success/failure fixtures. Proposed alert objectives must specify thresholds and recipients before operation; event delivery alone is not durable forensic retention. [L2, L4–L6]",
                "ar": "الحالة: سجل المهام وقياسات الاستخدام والتدقيق والمؤشرات وأحداث اللوحة منفذة. هدف القبول: تتبع كل مهمة وسير عمل اختباري بمعرّفه من الإرسال إلى النتيجة المخزنة، ومطابقة العدادات لسيناريوهات النجاح والفشل المضبوطة. ويجب تحديد حدود التنبيه ومستقبليه قبل التشغيل؛ فتسليم الحدث وحده لا يضمن احتفاظًا دائمًا للأغراض التحقيقية. [L2، L4–L6]",
            },
            {
                "heading": {"en": "NFR06 · Usability and accessibility", "ar": "NFR06 · سهولة الاستخدام وإمكانية الوصول"},
                "en": "Status: native desktop screens and widget tests exist; formal usability and accessibility studies are not established. Proposed acceptance: eight story walkthroughs complete without database edits; keyboard focus reaches every actionable control; errors distinguish policy, configuration and execution failure. Test readable layouts at 100% and 150% scaling. Provider-selection persistence remains an explicit behaviour to verify. [L4, L5]",
                "ar": "الحالة: تتوافر شاشات مكتبية أصلية واختبارات مكونات؛ ولا توجد دراسة رسمية مثبتة للاستخدام أو الوصول. القبول المقترح: إتمام القصص الثماني دون تعديل قاعدة البيانات، ووصول تركيز لوحة المفاتيح إلى كل عنصر قابل للتفاعل، وتمييز أخطاء السياسة والإعداد والتنفيذ. وتُختبر القراءة عند تكبير 100٪ و150٪. ويبقى حفظ اختيار المزود سلوكًا يتطلب تحققًا صريحًا. [L4، L5]",
            },
            {
                "heading": {"en": "NFR07 · Maintainability and portability", "ar": "NFR07 · قابلية الصيانة والنقل"},
                "en": "Status: controller, agent and Flutter desktop are separated and covered by targeted tests. Proposed acceptance: a clean environment reproduces dependency installation, linting and applicable tests using documented commands. Record skipped optional-MCP tests explicitly. Platform support requires a build-and-launch result for each claimed operating system; one Windows run does not validate all desktop targets. [L1, L3–L6]",
                "ar": "الحالة: المتحكم والوكيل وتطبيق Flutter منفصلة وتغطيها اختبارات موجهة. القبول المقترح: إعادة تثبيت الاعتماديات والفحص والاختبارات المناسبة بأوامر موثقة في بيئة نظيفة. ويجب التصريح باختبارات MCP الاختيارية المتجاوزة. كما يتطلب دعم المنصة نتيجة بناء وتشغيل لكل نظام معلن؛ فلا يثبت تشغيل Windows واحد صلاحية جميع الأنظمة المكتبية. [L1، L3–L6]",
            },
            {
                "heading": {"en": "NFR08 · Grounding quality and uncertainty", "ar": "NFR08 · جودة الارتكاز المعرفي وعدم اليقين"},
                "en": "Status: evidence limits, refusal handling and source-ID diagnostics exist, not semantic verification. Proposed evaluation: pre-register at least 30 supported, unsupported and injection-bearing synthetic cases; independently score factual support, citation correctness and appropriate abstention. Publish failures and model configuration. Any numerical release threshold should be agreed before evaluation, not selected retrospectively to make a model appear reliable. [L3, L5]",
                "ar": "الحالة: تتوافر حدود الأدلة ومعالجة الامتناع وتشخيص معرّفات المصادر، وليس التحقق الدلالي. التقييم المقترح: تعريف ثلاثين حالة اصطناعية على الأقل مسبقًا، تشمل الدعم والغياب ومحاولات حقن التعليمات، ثم تقييم الدعم الواقعي وصحة الاستشهاد والامتناع المناسب بصورة مستقلة. وتُنشر الإخفاقات وإعدادات النموذج. ويُتفق على حدود الإصدار الرقمية قبل التقييم، لا بأثر رجعي لإظهار موثوقية مصطنعة. [L3، L5]",
            },
        ],
    },
]
