import logging
from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict
from sqlalchemy.engine import make_url

from app.core.bootstrap import (
    WEAK_DB_PASSWORDS,
    ensure_runtime_secrets,
    is_placeholder,
)

logger = logging.getLogger("lycosa.config")


class Settings(BaseSettings):
    """Application settings, loaded from environment variables (and .env locally)."""

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    environment: str = "development"
    log_level: str = "info"

    # writable state (first-run generated secrets); a volume in Docker
    data_dir: str = "./data"

    api_host: str = "0.0.0.0"
    api_port: int = 8000

    database_url: str = "postgresql+asyncpg://lycosa:lycosa@localhost:5432/lycosa"
    qdrant_url: str = "http://localhost:6333"
    qdrant_api_key: str = ""

    # fallback for local dev only; must be >= 32 bytes for HS256 (RFC 7518)
    jwt_secret: str = "insecure-dev-only-secret-change-me-in-env"
    jwt_algorithm: str = "HS256"
    access_token_expire_minutes: int = 60

    default_admin_email: str = "admin@lycosa.local"
    default_admin_password: str = "change-me"

    rate_limit_enabled: bool = True
    rate_limit_requests: int = 120  # per window, per API key / client IP
    rate_limit_window_seconds: int = 60

    # node liveness (ADR-011): timeout should be ~3x the agent interval
    agent_heartbeat_interval_seconds: int = 5
    heartbeat_timeout_seconds: int = 15
    offline_sweep_interval_seconds: int = 5

    # task dispatch (ADR-012)
    task_dispatch_timeout_seconds: int = 120
    task_max_attempts: int = 3

    # knowledge plane (ADR-013)
    embedding_backend: str = "hashing"  # hashing | fastembed
    embedding_dim: int = 384
    # grounding (ADR-019): drop retrieved chunks scoring below this before they
    # reach an LLM. 0.0 keeps every chunk (the /retrieve API default); the
    # task-grounding path in the orchestrator applies it so out-of-scope queries
    # yield no context and trigger the grounded refusal instead of hallucination.
    retrieval_min_score: float = 0.0


def apply_runtime_secrets(settings: Settings) -> None:
    """Zero-config bootstrap (ADR-022): replace placeholder JWT/admin secrets
    with generated values persisted under the data dir."""
    need_jwt = is_placeholder(settings.jwt_secret)
    need_admin = is_placeholder(settings.default_admin_password)
    if not (need_jwt or need_admin):
        return
    data = ensure_runtime_secrets(settings.data_dir, need_jwt=need_jwt, need_admin=need_admin)
    if need_jwt:
        settings.jwt_secret = data["jwt_secret"]
    if need_admin:
        settings.default_admin_password = data["admin_password"]


def enforce_production_secrets(settings: Settings) -> None:
    """Fail fast on default/placeholder secrets when ENVIRONMENT=production (issue #7).

    JWT/admin secrets are auto-generated by apply_runtime_secrets, so in the
    normal startup path only the DB password can still be weak here; the auth
    checks remain as defense-in-depth.
    """
    if settings.environment.strip().lower() != "production":
        return
    problems = []
    try:
        db_password = make_url(settings.database_url).password or ""
    except Exception:
        db_password = ""
    if db_password in WEAK_DB_PASSWORDS:
        problems.append("DATABASE_URL/POSTGRES_PASSWORD uses a default password")
    if is_placeholder(settings.jwt_secret):
        problems.append("JWT_SECRET is a placeholder")
    if is_placeholder(settings.default_admin_password):
        problems.append("DEFAULT_ADMIN_PASSWORD is a placeholder")
    if problems:
        raise RuntimeError(
            "refusing to start with ENVIRONMENT=production: "
            + "; ".join(problems)
            + " — set strong values in .env (see .env.example)"
        )


@lru_cache
def get_settings() -> Settings:
    settings = Settings()
    apply_runtime_secrets(settings)
    enforce_production_secrets(settings)
    return settings
